sudo: false

language: d

os:
 - linux
 - osx
 
d:
 - dmd-2.068.2
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.15.1
 - gdc-5.2.0
 
matrix:
  allow_failures:
   - os: osx
     d: gdc-5.2.0
   - env: ARCH=x86
     d: gdc-5.2.0

addons:
  apt:
    packages:
     - gcc-multilib

notifications:
  email: false

env:
  global:
    - secure: "wnthDxOwv7qaVfJQfwYQLFo4DDBgfT4HoLntBsfmYjwmSVzCuXPktCK3vOpimb5twyiVNkt1I/82x8lyYpiczKqPcNZqd8p91mInt5eKIf8Gacqb3a1FwGyk9bwHSZdYpQiblY/wMVb0+WJTuhlVf1NI5xXMWCf1l88+1q6E6jo="
  matrix:
    - ARCH=x86
    - ARCH=x86_64

script:
 - dub test --arch=$ARCH;

after_success:
  - ./push-ddoc.sh
